# Generated by Django 5.0.3 on 2024-04-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('arabic_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='arabic name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/collection_images', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cateogry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('arabic_name', models.CharField(blank=True, max_length=90, null=True, verbose_name='arabic name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/cateogry_images', verbose_name='image')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='product.collection')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='title')),
                ('color', models.CharField(blank=True, max_length=90, null=True, verbose_name='color')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product_images', verbose_name='image')),
                ('tags', models.CharField(blank=True, help_text='ex: clothes, shoes, ....', max_length=255, null=True, verbose_name='tags')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('is_available', models.BooleanField(choices=[(True, 'avilable'), (False, 'not avilable')], default=True, verbose_name='is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sell_counter', models.IntegerField(default=0)),
                ('cateogry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.cateogry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductContentMultiLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='title')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('color', models.CharField(blank=True, max_length=200, null=True, verbose_name='color')),
                ('tags', models.CharField(blank=True, help_text='مثال: ملابس, ملابس شتاء, .......', max_length=255, null=True, verbose_name='tags')),
                ('language', models.CharField(blank=True, choices=[('ar', 'Arabic')], max_length=200, null=True, verbose_name='language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_content', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('available_qunatity', models.IntegerField(default=1, verbose_name='available qunatity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product.product')),
            ],
        ),
    ]
